import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/common/hero'
import HomeSection from '../components/home/home-section'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero pageTitle="J. Henry McKeen" mainSaying="Cognitive Psychologist by Training" subHead="UX Researcher by Profession" textBody="" imgUrl="/images/dark-background.jpg" imgAlt="dark background texture" url="index" />
      <HomeSection pageTitle="J. Henry McKeen" mainSaying="My name is James McKeen, but I go by my middle name, so you can call me Henry. I am a Cognitive Psychologist by training and a UX Researcher by profession.  I studied spatial cognition, specifically wayfinding and navigational processing. The line that I like to give people is that &ldquo;I spent my entire academic career documenting the cognitive strategies of people getting lost in complex, real-world environments. Now, I am spending my professional career documenting the cognitive strategies of people getting lost in complex, digital environments. The two have paralleled each other more than I ever would have imagined.&rdquo;" textBody="I love being a UX Researcher, because documenting the truth as it is perceived by others is one of the most invigorating tasks I’ve ever experienced. Don’t get me wrong, I am just as introspective as the next self-indulgent, anxiety magnet who spent their childhood being told they were “smart” and “precocious.” Pushing myself to direct that attention outward, devoting those mental resources to be focused on the realities of others in hopes of creating more positive experiences in the future, is incredibly rewarding. Sharing research insights with designers, developers, product managers and engineers; providing them with the information that helps them feel more confident in design decision-making is pretty wonderful, as well." imgUrl="/images/kingofcarbs-edit.png"/>
    </div>
  )
}
