import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/common/hero'
import HomeSection from '../components/common/home-section'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <HomeSection pageTitle="J. Henry McKeen" mainSaying="" textBody="My name is James McKeen, but I go by my middle name, so you can call me Henry. I am a Cognitive Psychologist by training and a UX Researcher by profession.  I studied spatial cognition, specifically wayfinding and navigational processing.  The line that I like to give people is that “I spent my entire academic career documenting the cognitive strategies of people getting lost in complex, real-world environments.  Now, I am spending my professional career documenting the cognitive strategies of people getting lost in complex, digital environments.  The two have paralleled each other more than I ever would have imagined." imgUrl="/images/svt.jpg" imgCaption="Test Image Caption"/>
    </div>
  )
}
