import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/common/hero'

export default function Writing() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero pageTitle="J. Henry McKeen" mainSaying="" textBody="Throughout our family's history we have many stories to show the impact of the men in our family. Take a journey through text, images, and family trees to find out what came before us." actionButton="Start Now"/>
    </div>
  )
}